### ISSUE TITLE
Struggling with creating a custom URL

### ISSUE THREAD

**Issue by inc16sec** [huncwotjs/huncwot#52]
I'm playing with Huncwot and so far so good. I would like to ask you how can I retrieve a user's data by passing a keyword after parameters. For instance, in Twitter, if you pass a username after Twitter (Twitter.com/user) you will go to their profile page (eg; Twitter.com/Zaiste) and if you add the "followers" keyword after username it will take you to followers page and bring that user's followers data (eg; Twitter.com/Zaiste/followers) I can go to users page by creating a folder (User) and giving it Controllers (browse.ts, fetch.ts ...) but how about (Followers) section ? How can I make a URL link with user/followers and bring the same user's followers ?. 
Thank you. Best regards.

**Comment by zaiste** [comment]
@inc16sec I'm working on a solution & an explanation. I need a bit more time. I appreciate your patience.

**Comment by inc16sec** [comment]
All good. Looking forward to what's to come.

**Comment by zaiste** [comment]
@inc16sec I'm sorry for the delay. It took longer than expected. I've just released a version `0.53`. This release adds an ability to use the nested routes properly. I've added a new section to `routes.ts` called `Resources`. This part configures how to exposes resources from the application features. Here's an example:

```js
Resources: [
    {
      feature: 'Planet',
      children: [
        { feature: 'Moon' }
      ]
    }
  ]
```

Such setup will make the following routes:

*For collections:*

* `GET` on `/planet/1/moon` triggers `Moon/Controller/browse.ts`
*  `POST` on `/planet/1/moon` triggers `Moon/Controller/create.ts`

*For members:*

* `GET` on `/moon/1` triggers  `Moon/Controller/fetch.ts`
* `PUT` on `/moon/1` triggers `Moon/Controller/update.ts`
* `DELETE` on `/moon/1` trigger `Moon/Controller/destroy.ts`

This approach follows how Rails defined so-called [*shallow* nested routes](https://guides.rubyonrails.org/routing.html#shallow-nesting). I've adopted it as it's the most practical solution I've seen. 

Also, if you'd like to use different names in the path; for example in order to use a plural form, I've added an `alias` attribute

```js
Resources: [
    {
      feature: 'Planet',
      alias: 'planets',
      children: [
        { feature: 'Moon', alias: 'moons' }
      ]
    }
  ]
```

Could you play with this and let me know your thoughts ?

**Comment by inc16sec** [comment]
I'm sorry but I didn't know how to actually call Resources section in `routes.ts`, by `routes.ts` do you mean the one in `config/server`  ?

**Comment by inc16sec** [comment]
After updating the package to version `0.53.0` and when I try to start the server with `huncwot server` or create a new project with `huncwot new "project name"` I get this error.

`internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module '@zerollup/ts-transform-paths'
Require stack:
- /usr/local/lib/node_modules/huncwot/cli/server.js
- /usr/local/lib/node_modules/huncwot/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/huncwot/cli/server.js:21:24)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/huncwot/cli/server.js',
    '/usr/local/lib/node_modules/huncwot/cli.js'
  ]
}`

**Comment by zaiste** [comment]
@inc16sec I'm sorry for the trouble, I've messed up some dependencies. Could you try `0.53.1` ? This version should fix it.

**Comment by inc16sec** [comment]
@zaiste `0.53.1` seems to be working just fine. But still, I don't know how to work with the `Resources []` section.  I've tried to look at `routes.ts` file in `config/server` I don't know if that's the right place where I should be looking.

**Comment by zaiste** [comment]
@inc16sec My mistake, I've missed your question. It's exactly that. Here's an example of `routes.ts` from `config/server`:

```js
import { Routes } from 'huncwot';
import { OK } from 'huncwot/response';

const routes: Routes = {
  GET: {
    // implicit `return` with a `text/plain` response
    '/hello': _ => 'Hello Huncwot',

    // explicit `return` with a 200 response of `application/json` type
    '/json': _ => {
      return OK({ a: 1, b: 2 });
    },

    // set your own headers
    '/headers': _ => {
      return { body: 'Hello B', statusCode: 201, headers: { 'Authorization': 'PASS' } };
    },
  },
  POST: {
    // request body is parsed in `params` by default
    '/bim': request => {
      return `Hello POST! ${request.params.name}`;
    }
  },
  Resources: [
    {
      feature: 'Planet',
      alias: 'planets',
      children: [
        { feature: 'Moon', alias: 'moons' }
      ]
    }
  ]
};

export default routes;
```

**Comment by inc16sec** [comment]
@zaiste Got it. 
One thing though. How to pass the params to `browse.ts` of the child.. Let's say i want to pass the `user Id` to get that user's followers. 

P.S. I like how requests return a response that shows you what you're missing `(eg; You need to create 'features/Followers/Controller/browse.js')`.. it is very helpful.

**Comment by zaiste** [comment]
@inc16sec Let's imagine the following URL `/users/zaiste/followers`, where `zaiste` is a dynamic segment. You need two controllers to handle that `User` and `Follower`. 

The URL should be handled by a *collection* route, i.e. you should use `browse.ts` of the `Follower` controller, and not `fetch.ts`. 

Since the resources are nested, there is an implicit `:id` segment added by Huncwot for convenience. Inside `browse.ts` of the `Follower` controller, you can then write:

```js
import { Handler } from 'huncwot';
import { OK } from 'huncwot/response';

const browse: Handler = async ({ params }) => {
  const { id } = params; // id will have the value of `zaiste`
  return ...
}

export = browse;
```

Here's the resource nesting required for this to work:

```
Resources: [
    {
      feature: 'User',
      alias: 'users',
      children: [
        { feature: 'Follower', alias: 'followers' }
      ]
    }
  ]
```

Let me know if you had more questions. I internalize too much stuff and often it is difficult for me to clearly communicate the intent. ;)

**Comment by inc16sec** [comment]
@zaiste Wonderful. It works like charm.. I've tried both `Followers` and `Following` as children and they both seem to work seamlessly. I'll go now and play more with huncwot, but i'll be back soon  😄, next we'll discuss security and authentication ;) 👍.

Thank you so much for making time to help and reply, as someone in need of help, I appreciate it with my life.

**Comment by zaiste** [comment]
@inc16sec Perfect! I'm glad it helped. Thanks for taking time to explore this tool. Your questions help me fill the gaps in the structure and in the docs. I appreciate it a lot.

Also, this project is still work in progress. Certain things need polishing. It's not yet ideal, but I hope it'll be perfect one day. ;) Even if you have minor questions, feel free to post them here.

**Comment by inc16sec** [comment]
@zaiste Where can I find the Argon2 package and how to use it? 

_ Also is it possible to work with Kerberos in Huncwot?. I'm looking into using it for Authentication with Neo4j.
